#### general settings
name: ediffsr_train_farm_multiband
use_tb_logger: true
model: denoising
distortion: sr
gpu_ids: [0]

sde:
  max_sigma: 50
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 16
  
#### datasets
datasets:
  train:
    optimizer: AdamW # Adam, AdamW, Lion
    name: Train_Dataset
    mode: LQGT
    # dataroot_GT: /workspace/AID_split_matched/HR/train
    # dataroot_LQ: /workspace/AID_split_matched/LR/train
    dataroot_GT: /workspace/Orthophotos_patches_tiff_scale16_split_ratio/HR/train
    dataroot_LQ: /workspace/Orthophotos_patches_tiff_scale16_split_ratio/LR/train

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 2
    GT_size: 256
    LR_size: 16
    use_flip: true
    use_rot: true
    use_noise: False
    use_bright: False
    use_blur: False
    color: Multiband
    img_channel: 7 #add my selelf
  val:
    name: Val_Dataset
    mode: LQGT
    # dataroot_GT: /workspace/AID_split_matched/HR/val
    # dataroot_LQ: /workspace/AID_split_matched/LR/val
    dataroot_GT: /workspace/Orthophotos_patches_tiff_scale16_split_ratio/HR/val
    dataroot_LQ: /workspace/Orthophotos_patches_tiff_scale16_split_ratio/LR/val
    color: Multiband
    img_channel: 7 #add my selelf


#### network structures
network_G:
  which_model_G: ConditionalNAFNet
  setting:
    width: 64
    enc_blk_nums: [14, 1, 1, 1]
    middle_blk_num: 1
    dec_blk_nums: [1, 1, 1, 1]
    img_channel: 7

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  # strict_load: false
  #resume_state: /home/amax/Desktop/16T/disk3/XY-SPACE/SISR/image-restoration-sde-main/codes/config/sisr/log/refusion/training_state/360000.state
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: AdamW # Adam, AdamW, Lion
  lr_G: !!float 4e-5
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.99
  niter: 700000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 300000, 400000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
